### ISSUE TITLE
Possible to submit multiple, independent projects?

### ISSUE THREAD

**Issue by mkurz** [scalacenter/sbt-dependency-submission#84] opened 2023-02-28 11:40 UTC
Sorry for my ignorance in case that is possible anyway and I just couldn't figure it out or was misconfiguring things or was discussed already.

Let's say I have a repository with two independent projects `project_a/build.sbt` and `project_b/build.sbt`.
Can I submit both of those `build.sbt` files to GitHub so they show up independent in the /network/dependencies view?
I tried that with the Play Framework were we have a `build.sbt` and a `documentation/build.sbt`, but in the GitHub UI only the `build.sbt` shows up.
The workflow: https://github.com/playframework/playframework/blob/3c21f31f28c27ad00c9495096fa60e25a4b67050/.github/workflows/dependency-graph.yml#L24-L27

I think this has to be possible somehow because in our Dependency UI it shows all our (multiple) yml workflow files already.

**Comment by adpi2** [comment] 2023-02-28 12:32
Thanks for opening this issue. It should indeed be possible to submit multiple independent projects but currently it is not.

The problem is that currently all manifests are declared as coming from a single build file `build.sbt`:
https://github.com/scalacenter/sbt-dependency-submission/blob/04f2579de8e5d7ce6049129ff1b6912520d21dfd/sbt-plugin/src/main/scala/ch/epfl/scala/GithubDependencyGraphPlugin.scala#L186-L187

I thing we can fix this by comparing the sbt `baseDirectory` with the `GITHUB_WORKSPACE` from [Github default env variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).

**Comment by mkurz** [comment] 2023-03-01 23:35
@adpi2 Thanks! Would be nice to have this working :wink:

**Comment by mkurz** [comment] 2023-03-24 10:55
Thanks for fixing. However how does that actually work now?
Do I need to run a separate step for each project? E.g.
```yml
...
steps:
  - uses: actions/checkout@v3
  - uses: scalacenter/sbt-dependency-submission@v2
    with:
      working-directory: ./my-scala-project-one
  - uses: scalacenter/sbt-dependency-submission@v2
    with:
      working-directory: ./my-scala-project-two
```
Or does the action detect all `build.sbt` files automatically?

**Comment by adpi2** [comment] 2023-03-24 11:05
> Thanks for fixing. However how does that actually work now?
Do I need to run a separate step for each project? E.g.

Yes you still need to run a separate step for each project.

The fix is released in 2.2.1. @mkurz Could you test that it works as expected?

**Comment by mkurz** [comment] 2023-03-24 12:47
@adpi2 Exactly, see my comment https://github.com/playframework/play-mailer/pull/250#issuecomment-1482742155

**Comment by adpi2** [comment] 2023-03-24 13:05
@mkurz, thanks for the comment. Being able to send the manifests of several build in a single snapshot would require quite some changes in the architecture of the action. I could try it but I think there is a simpler fix.

Currently we use the pair GITHUB_RUN_ID and GITHUB_JOB as identifiers of a snapshot. In your job there are possibly both the same and that would be why the snapshots get overwritten.

**Comment by adpi2** [comment] 2023-03-24 13:44
Found some interesting [documentation](https://docs.github.com/en/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28#create-a-snapshot-of-dependencies-for-a-repository) about that problem:
> Correlator provides a key that is used to group snapshots submitted over time. Only the "latest" submitted snapshot for a given combination of job.correlator and detector.name will be considered when calculating a repository's current dependencies. Correlator should be as unique as it takes to distinguish all detection runs for a given "wave" of CI workflow you run. If you're using GitHub Actions, a good default value for this could be the environment variables GITHUB_WORKFLOW and GITHUB_JOB concatenated together. If you're using a build matrix, then you'll also need to add additional key(s) to distinguish between each submission inside a matrix variation.

**Closed** 2023-03-24 14:22 UTC

**Comment by adpi2** [comment] 2023-03-24 14:51
@mkurz If you can try again to run your dependency submission that would be very helpful

**Comment by mkurz** [comment] 2023-03-24 15:13
@adpi2 It's working now :tada: 
* https://github.com/playframework/play-mailer/actions/runs/4511227545/jobs/7946346475
* https://github.com/playframework/play-mailer/network/dependencies

Thanks!
